### ISSUE TITLE
Instructions not found

### ISSUE THREAD

**Issue by MohamedElashri** [dracula/zed#4]
It does seem that instructions are not available on https://draculatheme.com/zed. Maybe it is not approved yet.

**Comment by Otterpocket** [comment]
Hey @MohamedElashri, yes I have contacted the team about the missing page. I assume it's work in progress.

I assume you know how to install it, if not give me shout.

**Comment by MohamedElashri** [comment]
> Hey @MohamedElashri, yes I have contacted the team about the missing page. I assume it's work in progress.

Hi Yes, I did it via 

```
curl -o ~/.config/zed/themes/dracula.json https://raw.githubusercontent.com/dracula/zed/main/themes/dracula.json
```

**Comment by Otterpocket** [comment]
Thanks for getting in touch, I'll leave this issue open until the page is up on the dracula website

**Comment by MohamedElashri** [comment]
> There are currently 2 ways to install it.
> ### Using Zed Preview version
> 
> If you are on the preview version you can open the extensions view. ![image](https://private-user-images.githubusercontent.com/7274458/305142484-0da0a196-d8a5-4194-ac6c-d0f9e5f22863.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgwMTQzMTQsIm5iZiI6MTcwODAxNDAxNCwicGF0aCI6Ii83Mjc0NDU4LzMwNTE0MjQ4NC0wZGEwYTE5Ni1kOGE1LTQxOTQtYWM2Yy1kMGY5ZTVmMjI4NjMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIxNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMTVUMTYyMDE0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjA0YzA1ZDUxNWU0OTRlNTYzZTA0Y2ZjYjUyYTAyZWYwMTU5YzA4MTY5ZjRjZTc1OTk2OTAxZGY3ZDgyZWU2MiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.uSaytJ9MAdMUaXu2tHe36vMAr4oLJnmXp-7vp2qdpNQ) <img alt="image" width="1165" src="https://private-user-images.githubusercontent.com/7274458/305142689-a00be750-af52-4b6f-aa2a-16a3f99b5332.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgwMTQzMTQsIm5iZiI6MTcwODAxNDAxNCwicGF0aCI6Ii83Mjc0NDU4LzMwNTE0MjY4OS1hMDBiZTc1MC1hZjUyLTRiNmYtYWEyYS0xNmEzZjk5YjUzMzIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIxNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMTVUMTYyMDE0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTFjMjgwNTQ0MWJmZDg4NGQzNGRmZWUyYjQyYzRjZWU0ZDYxN2RlNzVjYmY0ZWFlMDZmNGYxY2EzNjZhNWJjYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.GDdIbrDsNu8IRu4pQJU4oqEA97nMTCmZEDa4sDzj-7k">
> ### Not using Zed Preview version
> 
> (extensions store is not yet on stable) add the `dracula.json` file to ` ~/.config/zed/themes`

Great, thanks for details, is there a requirement by dracula project not to put install instructions in `README.md`? I think this would be great if added there

**Comment by Otterpocket** [comment]
> > There are currently 2 ways to install it.
> > ### Using Zed Preview version
> > If you are on the preview version you can open the extensions view. 
> > ### Not using Zed Preview version
> > (extensions store is not yet on stable) add the `dracula.json` file to ` ~/.config/zed/themes`
> 
> Great, thanks for details, is there a requirement by dracula project not to put install instructions in `README.md`? I think this would be great if added there

None of the other repo's seem have the install instructions in the readme, so I assume it's the prefered convention
